"use client";

import { useEffect, useState } from "react";

import { useRouter } from "next/navigation";

import { Controller, useForm, useWatch } from "react-hook-form";

import { zodResolver } from "@hookform/resolvers/zod";
import { z } from "zod";
import { toast } from "sonner";

import { Input } from "@/src/components/ui/input";
import { Select } from "@/src/components/ui/select";
import { Switch } from "@/src/components/ui/switch";
import { Textarea } from "@/src/components/ui/textarea";
import { Button } from "@/src/components/ui/button";

import { Combobox, type ComboboxOption } from "@/src/components/ui/combobox";

import { LeadTagPill } from "@/src/components/leads/lead-tag-pill";

import { addLeadSchema, addLeadDefaults, type AddLeadValues } from "@/src/lib/validation/lead";

import { searchCustomersForLead, searchCarsForLead, createLead } from "@/app/admin/leads/new/actions";

import type { AddLeadLookups } from "@/src/lib/supabase/lead-lookups";

/* =========================================================
   TYPES
========================================================= */

/*
 * Important:
 *
 * Zod schemas that use .default() can have different
 * INPUT and OUTPUT types.
 *
 * Example:
 *
 * input:
 *   tag_ids?: string[]
 *
 * output:
 *   tag_ids: string[]
 *
 * React Hook Form receives the input shape.
 * createLead() receives the parsed output shape.
 */
type AddLeadFormInput = z.input<typeof addLeadSchema>;

interface AddLeadFormProps {
  lookups: AddLeadLookups;
  defaultStageId: string;
}

/* =========================================================
   COMPONENT
========================================================= */

export function AddLeadForm({ lookups, defaultStageId }: AddLeadFormProps) {
  const router = useRouter();

  const [isSaving, setIsSaving] = useState(false);

  const [customerOptions, setCustomerOptions] = useState<ComboboxOption[]>([]);

  const [carOptions, setCarOptions] = useState<ComboboxOption[]>([]);

  /* =========================================================
     FORM
  ========================================================= */

  const {
    control,
    register,
    handleSubmit,

    formState: { errors },
  } = useForm<AddLeadFormInput, unknown, AddLeadValues>({
    resolver: zodResolver(addLeadSchema),

    defaultValues: {
      ...addLeadDefaults,

      stage_id: defaultStageId,
    },
  });

  /* =========================================================
     WATCHED VALUES
  ========================================================= */

  /*
   * useWatch is used instead of useForm().watch().
   *
   * This avoids the React Compiler incompatible-library
   * warning generated by watch().
   */

  const createNewCustomer =
    useWatch({
      control,
      name: "create_new_customer",
    }) ?? false;

  const selectedSourceId =
    useWatch({
      control,
      name: "source_id",
    }) ?? null;

  /* =========================================================
     SOURCE DETAIL
  ========================================================= */

  const sourceRequiresDetail =
    lookups.sources.find((source) => source.id === selectedSourceId)?.requires_detail ?? false;

  /* =========================================================
     LOAD CUSTOMER + VEHICLE OPTIONS
  ========================================================= */

  useEffect(() => {
    searchCustomersForLead()
      .then((customers) => {
        setCustomerOptions(
          customers.map((customer) => ({
            id: customer.id,

            label: `${customer.full_name} · ${customer.customer_number} · ${customer.phone}`,
          })),
        );
      })
      .catch((error: unknown) => {
        console.error("Unable to load customers:", error);

        setCustomerOptions([]);
      });

    searchCarsForLead()
      .then((cars) => {
        setCarOptions(
          cars.map((car) => ({
            id: car.id,

            label: `${car.display_title} · ${car.stock_id}`,
          })),
        );
      })
      .catch((error: unknown) => {
        console.error("Unable to load vehicles:", error);

        setCarOptions([]);
      });
  }, []);

  /* =========================================================
     TAG TOGGLE
  ========================================================= */

  const toggleTag = (tagId: string, current: string[], onChange: (next: string[]) => void) => {
    const next = current.includes(tagId) ? current.filter((id) => id !== tagId) : [...current, tagId];

    onChange(next);
  };

  /* =========================================================
     SUBMIT
  ========================================================= */

  const onSubmit = handleSubmit(
    async (values) => {
      setIsSaving(true);

      try {
        /*
         * Because useForm's third generic is AddLeadValues,
         * values here is the validated Zod OUTPUT type.
         */
        const result = await createLead(values);

        if (result.error) {
          toast.error(result.error);

          return;
        }

        if (!result.leadId) {
          toast.error("Lead was created but its ID could not be resolved.");

          return;
        }

        toast.success("Lead created successfully");

        router.push(`/admin/leads/${result.leadId}`);
      } finally {
        setIsSaving(false);
      }
    },

    () => {
      toast.error("Please fix the highlighted fields.");
    },
  );

  /* =========================================================
     RENDER
  ========================================================= */

  return (
    <form onSubmit={onSubmit} className="flex flex-col gap-6 pb-10">
      {/* =====================================================
          CUSTOMER
      ===================================================== */}

      <div className="surface-card flex flex-col gap-4 p-5">
        <div className="flex items-center justify-between">
          <p className="text-label">Customer</p>

          <Controller
            control={control}
            name="create_new_customer"
            render={({ field }) => (
              <Switch
                label="Create New Customer"
                checked={Boolean(field.value)}
                onCheckedChange={field.onChange}
              />
            )}
          />
        </div>

        {createNewCustomer ? (
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
            <Input
              label="First Name"
              required
              {...register("new_first_name")}
              error={errors.new_first_name?.message}
            />

            <Input
              label="Last Name"
              required
              {...register("new_last_name")}
              error={errors.new_last_name?.message}
            />

            <Input
              label="Email"
              type="email"
              required
              {...register("new_email")}
              error={errors.new_email?.message}
            />

            <Input label="Phone" required {...register("new_phone")} error={errors.new_phone?.message} />
          </div>
        ) : (
          <Controller
            control={control}
            name="customer_id"
            render={({ field }) => (
              <Combobox
                label="Search Customer"
                placeholder="Search by name, ID, or phone..."
                value={field.value ?? null}
                onChange={field.onChange}
                options={customerOptions}
                error={errors.customer_id?.message}
              />
            )}
          />
        )}
      </div>

      {/* =====================================================
          VEHICLE
      ===================================================== */}

      <div className="surface-card flex flex-col gap-4 p-5">
        <p className="text-label">Vehicle of Interest</p>

        <Controller
          control={control}
          name="car_id"
          render={({ field }) => (
            <Combobox
              label="Search Inventory"
              placeholder="Optional — search by name or stock ID..."
              value={field.value ?? null}
              onChange={field.onChange}
              options={carOptions}
            />
          )}
        />

        <p className="text-caption text-text-subtle">
          Leave blank if the customer hasn&apos;t settled on a specific vehicle yet — it can be added later.
        </p>
      </div>

      {/* =====================================================
          LEAD DETAILS
      ===================================================== */}

      <div className="surface-card flex flex-col gap-4 p-5">
        <p className="text-label">Lead Details</p>

        <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
          {/* SOURCE */}

          <Controller
            control={control}
            name="source_id"
            render={({ field }) => (
              <Select
                label="Source"
                placeholder="Select a source"
                options={lookups.sources.map((source) => ({
                  value: source.id,

                  label: source.name,
                }))}
                value={field.value ?? ""}
                onChange={(event) => field.onChange(event.target.value || null)}
              />
            )}
          />

          {/* SOURCE DETAIL */}

          {sourceRequiresDetail && <Input label="Specify Source" {...register("source_detail")} />}

          {/* STAGE */}

          <Controller
            control={control}
            name="stage_id"
            render={({ field }) => (
              <Select
                label="Stage"
                options={lookups.stages.map((stage) => ({
                  value: stage.id,

                  label: stage.name,
                }))}
                value={field.value ?? ""}
                onChange={(event) => field.onChange(event.target.value)}
                error={errors.stage_id?.message}
              />
            )}
          />

          {/* TEMPERATURE */}

          <Controller
            control={control}
            name="temperature"
            render={({ field }) => (
              <Select
                label="Temperature"
                options={[
                  {
                    value: "Hot",
                    label: "Hot",
                  },
                  {
                    value: "Warm",
                    label: "Warm",
                  },
                  {
                    value: "Cold",
                    label: "Cold",
                  },
                ]}
                value={field.value ?? "Warm"}
                onChange={(event) => field.onChange(event.target.value)}
              />
            )}
          />

          {/* ASSIGNED STAFF */}

          <Controller
            control={control}
            name="assigned_staff_id"
            render={({ field }) => (
              <Select
                label="Assigned Staff"
                placeholder="Unassigned"
                options={lookups.staff.map((staff) => ({
                  value: staff.id,

                  label: staff.full_name,
                }))}
                value={field.value ?? ""}
                onChange={(event) => field.onChange(event.target.value || null)}
              />
            )}
          />
        </div>

        {/* ===================================================
            TAGS
        =================================================== */}

        <div>
          <p className="text-label mb-2">Tags</p>

          <Controller
            control={control}
            name="tag_ids"
            render={({ field }) => {
              const currentTagIds = field.value ?? [];

              return (
                <div className="flex flex-wrap gap-2">
                  {lookups.tags.map((tag) => {
                    /*
                     * AddLeadLookups currently exposes
                     * id/name/color_hex but LeadTagPill's
                     * LeadTag requires slug too.
                     *
                     * If the lookup starts returning slug,
                     * use it. Otherwise derive a stable
                     * display slug from the name.
                     */
                    const slug =
                      "slug" in tag && typeof tag.slug === "string"
                        ? tag.slug
                        : tag.name
                            .trim()
                            .toLowerCase()
                            .replace(/[^a-z0-9]+/g, "-")
                            .replace(/^-+|-+$/g, "");

                    return (
                      <LeadTagPill
                        key={tag.id}
                        tag={{
                          id: tag.id,

                          name: tag.name,

                          slug,

                          color_hex: tag.color_hex,
                        }}
                        selected={currentTagIds.includes(tag.id)}
                        onClick={() => toggleTag(tag.id, currentTagIds, field.onChange)}
                      />
                    );
                  })}
                </div>
              );
            }}
          />
        </div>
      </div>

      {/* =====================================================
          FOLLOW-UP
      ===================================================== */}

      <div className="surface-card flex flex-col gap-4 p-5">
        <p className="text-label">Initial Follow-Up</p>

        <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
          <Input label="Date" type="date" {...register("follow_up_date")} />

          <Input label="Time" type="time" {...register("follow_up_time")} />
        </div>

        <p className="text-caption text-text-subtle">
          Optional — scheduling it here saves a step; it can also be added afterward from the lead&apos;s own
          page.
        </p>
      </div>

      {/* =====================================================
          NOTES
      ===================================================== */}

      <div className="surface-card flex flex-col gap-4 p-5">
        <p className="text-label">Notes</p>

        <Textarea placeholder="Anything worth recording about this lead..." {...register("notes")} rows={3} />
      </div>

      {/* =====================================================
          ACTIONS
      ===================================================== */}

      <div className="flex justify-end gap-2">
        <Button
          type="button"
          variant="outline"
          disabled={isSaving}
          onClick={() => router.push("/admin/leads")}
        >
          Cancel
        </Button>

        <Button type="submit" isLoading={isSaving} disabled={isSaving}>
          Create Lead
        </Button>
      </div>
    </form>
  );
}
